/**
 * Staff report detail — summary KPIs, period, recipients, and key payload fields.
 */

import { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  View,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';

import { StaffDetailScreen } from '@/components/staff-ui';
import { ThemedText } from '@/components/themed-text';
import { ClientUI } from '@/constants/client-ui';
import { Fonts } from '@/constants/theme';
import { apiGetStaffReport, type ApiManagedStaffReport } from '@/lib/data/api';
import { formatMinorMWK } from '@/lib/money/formatMinorMWK';
import { getStoredAuth } from '@/lib/storage';

function moneyish(value: unknown): string | null {
  if (value == null) return null;
  const n = Number(value);
  if (!Number.isFinite(n)) return String(value);
  // Heuristic: values >= 1000 treated as minor units (tambala) for MWK display.
  if (Math.abs(n) >= 1000 && Number.isInteger(n)) return formatMinorMWK(n);
  return String(n);
}

function formatTs(value?: string | null): string {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toLocaleString();
}

function SummaryGrid({ summary }: { summary?: Record<string, unknown> | null }) {
  if (!summary || !Object.keys(summary).length) {
    return <ThemedText style={styles.muted}>No summary metrics on this pack.</ThemedText>;
  }
  const preferred = [
    'loan_count',
    'active_loan_count',
    'outstanding_minor',
    'par_30_pct',
    'par_60_pct',
    'par_90_pct',
    'headline_par_30_pct',
    'collected_minor',
    'repayment_count',
    'disbursed_minor',
    'disbursement_count',
    'application_count',
  ];
  const keys = [
    ...preferred.filter((k) => summary[k] != null),
    ...Object.keys(summary).filter((k) => !preferred.includes(k)).slice(0, 12),
  ];
  return (
    <View style={styles.grid}>
      {keys.map((key) => {
        const raw = summary[key];
        const isPct = key.includes('pct') || key.includes('percent');
        const isMoney = key.includes('minor') || key.includes('amount') || key.includes('balance');
        let display: string;
        if (isPct) display = `${raw}%`;
        else if (isMoney) display = moneyish(raw) ?? '—';
        else display = String(raw);
        return (
          <View key={key} style={styles.kpi}>
            <ThemedText style={styles.kpiValue}>{display}</ThemedText>
            <ThemedText style={styles.kpiLabel}>{key.replace(/_/g, ' ')}</ThemedText>
          </View>
        );
      })}
    </View>
  );
}

export default function StaffReportDetailScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ id: string }>();
  const id = Number(params.id);
  const [report, setReport] = useState<ApiManagedStaffReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showPayload, setShowPayload] = useState(false);

  const load = useCallback(async () => {
    if (!Number.isFinite(id) || id <= 0) {
      setError('Invalid report id');
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const auth = await getStoredAuth();
      if (!auth?.token) {
        setError('Sign in required.');
        return;
      }
      const detail = await apiGetStaffReport(auth.token, id);
      setReport(detail);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load report');
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <StaffDetailScreen
      title={report?.title || 'Staff report'}
      subtitle={
        report
          ? `${report.catalog_key.replace(/_/g, ' ')} · ${report.status.replace(/_/g, ' ')}`
          : 'Pack detail'
      }
    >
      {loading && !report ? (
        <View style={styles.center}>
          <ActivityIndicator color={ClientUI.colors.primary} />
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={styles.body}
          refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} />}
        >
          {error ? <ThemedText style={styles.error}>{error}</ThemedText> : null}

          {report ? (
            <>
              <View style={styles.metaCard}>
                <ThemedText style={styles.metaLine}>
                  Generated by {report.generated_by_name || '—'} (
                  {(report.generated_by_role || '').replace(/_/g, ' ') || '—'})
                </ThemedText>
                <ThemedText style={styles.metaLine}>
                  Generated {formatTs(report.generated_at)}
                </ThemedText>
                {(report.period_from || report.period_to) && (
                  <ThemedText style={styles.metaLine}>
                    Period{' '}
                    {report.period_from
                      ? new Date(report.period_from).toLocaleDateString()
                      : '—'}{' '}
                    →{' '}
                    {report.period_to ? new Date(report.period_to).toLocaleDateString() : '—'}
                  </ThemedText>
                )}
                {report.forward_message ? (
                  <ThemedText style={styles.msg}>{report.forward_message}</ThemedText>
                ) : null}
              </View>

              <ThemedText style={styles.section}>Key metrics</ThemedText>
              <SummaryGrid summary={report.summary} />

              {(report.recipients?.length ?? 0) > 0 ? (
                <>
                  <ThemedText style={styles.section}>Recipients</ThemedText>
                  {report.recipients!.map((r) => (
                    <View key={r.id} style={styles.recipient}>
                      <MaterialIcons name="person-outline" size={18} color={ClientUI.colors.primary} />
                      <View style={{ flex: 1 }}>
                        <ThemedText style={styles.cardTitle}>
                          {(r.to_staff_name || r.to_role).replace(/_/g, ' ')}
                        </ThemedText>
                        <ThemedText style={styles.muted}>
                          {r.status.replace(/_/g, ' ')}
                          {r.reviewed_at ? ` · ${formatTs(r.reviewed_at)}` : ''}
                        </ThemedText>
                        {r.notes ? <ThemedText style={styles.muted}>{r.notes}</ThemedText> : null}
                      </View>
                    </View>
                  ))}
                </>
              ) : null}

              <Pressable style={styles.toggle} onPress={() => setShowPayload((v) => !v)}>
                <ThemedText style={styles.toggleText}>
                  {showPayload ? 'Hide payload preview' : 'Show payload preview'}
                </ThemedText>
                <MaterialIcons
                  name={showPayload ? 'expand-less' : 'expand-more'}
                  size={22}
                  color={ClientUI.colors.primary}
                />
              </Pressable>
              {showPayload && report.payload ? (
                <View style={styles.payloadBox}>
                  <ThemedText style={styles.payloadText} selectable>
                    {JSON.stringify(report.payload, null, 2).slice(0, 6000)}
                  </ThemedText>
                </View>
              ) : null}

              <Pressable style={styles.backLink} onPress={() => router.back()}>
                <ThemedText style={styles.backLinkText}>Back to hub</ThemedText>
              </Pressable>
            </>
          ) : null}
        </ScrollView>
      )}
    </StaffDetailScreen>
  );
}

const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  body: { padding: 16, paddingBottom: 48, gap: 10 },
  section: {
    marginTop: 8,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    fontSize: 14,
    color: ClientUI.colors.text,
  },
  metaCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ClientUI.colors.border,
    backgroundColor: ClientUI.colors.surface,
    padding: 12,
    gap: 4,
  },
  metaLine: { fontFamily: Fonts.sans, fontSize: 13, color: ClientUI.colors.textMuted },
  msg: {
    marginTop: 8,
    padding: 8,
    borderRadius: 8,
    backgroundColor: ClientUI.colors.surfaceMuted,
    fontSize: 12,
    color: ClientUI.colors.text,
    fontFamily: Fonts.sans,
  },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  kpi: {
    width: '47%',
    flexGrow: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ClientUI.colors.border,
    backgroundColor: ClientUI.colors.surface,
    padding: 12,
  },
  kpiValue: { fontFamily: Fonts.sans, fontSize: 16, fontWeight: '800', color: ClientUI.colors.text },
  kpiLabel: {
    fontFamily: Fonts.sans,
    fontSize: 11,
    color: ClientUI.colors.textMuted,
    marginTop: 2,
    textTransform: 'capitalize',
  },
  recipient: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: ClientUI.colors.border,
    borderRadius: 12,
    padding: 12,
    backgroundColor: ClientUI.colors.surface,
  },
  cardTitle: { fontFamily: Fonts.sans, fontWeight: '700', fontSize: 14, color: ClientUI.colors.text },
  muted: { fontFamily: Fonts.sans, fontSize: 12, color: ClientUI.colors.textMuted, marginTop: 2 },
  toggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  toggleText: {
    fontFamily: Fonts.sans,
    fontWeight: '700',
    color: ClientUI.colors.primary,
    fontSize: 14,
  },
  payloadBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ClientUI.colors.border,
    backgroundColor: ClientUI.colors.surfaceMuted,
    padding: 12,
    maxHeight: 360,
  },
  payloadText: {
    fontFamily: Fonts.mono || Fonts.sans,
    fontSize: 11,
    color: ClientUI.colors.text,
    lineHeight: 16,
  },
  backLink: { alignItems: 'center', paddingVertical: 12 },
  backLinkText: { fontFamily: Fonts.sans, color: ClientUI.colors.primary, fontWeight: '700' },
  error: { color: ClientUI.colors.danger, fontFamily: Fonts.sans },
});
